events {
    worker_connections 1024;
}

http {
    upstream ml_backend {
        server ml-api:5000;
    }

    server {
        listen 80;

        location /health {
            proxy_pass http://ml_backend;
        }

        location /predict {
            proxy_pass http://ml_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}